apiVersion: v1
kind: Service
metadata:
  name: knote
spec:
  selector:
    app: knote
  ports:
    - port: {{ .Values.knote.service.port }}
      targetPort: {{ .Values.knote.service.targetPort }}
  type: {{ .Values.knote.service.type }}
